# Generated by Django 4.1.1 on 2022-09-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="reviews", name="image",),
        migrations.RemoveField(model_name="reviews", name="is_active",),
        migrations.RemoveField(model_name="reviews", name="slug",),
    ]
