# Generated by Django 4.1.1 on 2022-09-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_reviews_image_remove_reviews_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews"),
        ),
        migrations.AddField(
            model_name="reviews",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reviews",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
